name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter (update version)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'  # ✅ ใช้ตามที่แนะนำ
          channel: stable

      # 3️⃣ Flutter Doctor
      - name: Flutter Doctor
        run: flutter doctor -v

      # 4️⃣ Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 5️⃣ Build web
      - name: Build Web
        run: flutter build web --release

      # 6️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
